# Site settings
author: Renee Sims
title: Bit Love Blog
header-img: img/home-bg.png
email: info@reneesoul.com
copyright_name: Renee Sims
description: > # this means to ignore newlines until "baseurl:"
  Getting to the next great processes!
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alouiscious

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
